vich_uploader:
    db_driver: orm

    mappings:
       users_avatar:
           uri_prefix: /images/users_avatar
           upload_destination: '%kernel.project_dir%/public/images/users_avatar'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
